sudo: require
dist: trusty
language: cpp
compiler: gcc
before_install:
    - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
    - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
    - gcc --version
    - g++ --version
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake
    - sudo apt-get install -y libgtest-dev
    - sudo apt-get install python2.7
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -
before_script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ls -l
    - cd ..
    - sudo python2.7 setup.py install
script:
    - ./build/tests/jamspell_tests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
